In [1]:
import numpy as np
import math
from sklearn.preprocessing import StandardScaler

In [2]:
X = np.array(([1,2,4],[1,4,5]))
Y = np.array(([0], [1]))
theta = np.zeros((3, 1))

In [3]:
scalerX = StandardScaler().fit(X)
scalerY = StandardScaler().fit(Y)

/opt/anaconda/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [4]:
Xs = scalerX.transform(X)
Ys = scalerY.transform(Y)

/opt/anaconda/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [5]:
Xs, Ys

(array([[ 0., -1., -1.],
        [ 0.,  1.,  1.]]), array([[-1.],
        [ 1.]]))

In [6]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [7]:
def logisticRegression(X, theta):
    return sigmoid(X@theta)

In [8]:
def costFunction(X, Y, theta):
    z = X@theta
    h = sigmoid(z)
    return (1/X.shape[0])*(-Y.T@np.log(h)-(1-Y).T@np.log(1-h)+(lam/2)*theta.T@theta)

In [9]:
def log_likelihood(features, target, weights):
    scores = np.dot(features, weights)
    ll = np.sum( target*scores - np.log(1 + np.exp(scores)) )
    return ll

In [10]:
def loss(X, y, theta):
    h = X@theta
    return (-y * np.log(h) - (1 - y) * np.log(1 - h)).mean()

In [11]:
def cost(x, y, theta):
    h = x@theta
    one_case = np.matmul(-y.T, np.log(h))
    zero_case = np.matmul(-(1 - y).T, np.log(1 - h))
    return (one_case + zero_case) / len(x)

In [12]:
def gradient(x, y, theta, lr, lam):
    h = logisticRegression(x,theta)
    derivative = x.T@(h-y)
    return theta - (lr/X.shape[0])*derivative

In [13]:
logisticRegression(X, theta)

array([[0.5],
       [0.5]])

In [14]:
h = logisticRegression(X,theta)
X.T@(h-Y)

array([[ 0. ],
       [-1. ],
       [-0.5]])

In [36]:
for i in range(10):
    print(costFunction(Xs, Ys, theta))
    theta = gradient(Xs, Ys, theta, 0.0001, 0)

print(costFunction(Xs, Ys, theta))

[[-3.17784486]]
[[-3.17955343]]
[[-3.1812561]]
[[-3.18295291]]
[[-3.18464389]]
[[-3.18632909]]
[[-3.18800855]]
[[-3.1896823]]
[[-3.19135038]]
[[-3.19301284]]
[[-3.1946697]]


In [38]:
theta

array([[0.        ],
       [0.02977911],
       [0.02977911]])

In [16]:
class LogisticRegression:
    def __init__(self, lr=0.01, num_iter=100000, fit_intercept=True, verbose=False):
        self.lr = lr
        self.num_iter = num_iter
        self.fit_intercept = fit_intercept
        self.verbose = verbose
    
    def __add_intercept(self, X):
        intercept = np.ones((X.shape[0], 1))
        return np.concatenate((intercept, X), axis=1)
    
    def __sigmoid(self, z):
        return 1 / (1 + np.exp(-z))
    def __loss(self, h, y):
        return (-y * np.log(h) - (1 - y) * np.log(1 - h)).mean()
    
    def fit(self, X, y):
        if self.fit_intercept:
            X = self.__add_intercept(X)
        
        # weights initialization
        self.theta = np.zeros(X.shape[1])
        
        for i in range(self.num_iter):
            z = np.dot(X, self.theta)
            h = self.__sigmoid(z)
            gradient = np.dot(X.T, (h - y)) / y.size
            self.theta -= self.lr * gradient
            
            z = np.dot(X, self.theta)
            h = self.__sigmoid(z)
            loss = self.__loss(h, y)
                
            if(self.verbose ==True and i % 10000 == 0):
                print(f'loss: {loss} \t')
    
    def predict_prob(self, X):
        if self.fit_intercept:
            X = self.__add_intercept(X)
    
        return self.__sigmoid(np.dot(X, self.theta))
    
    def predict(self, X):
        return self.predict_prob(X).round()

In [ ]:
lr = LogisticRegression