In [1]:
import numpy as np
from scipy.optimize import fmin_l_bfgs_b

In [2]:
def f(x):
    return (x**2+1).sum()

In [3]:
x0=np.array([[1],[2]])

In [4]:
fmin_l_bfgs_b(f,x0,approx_grad=True)[0]

array([1.49904489e-08, 2.99808978e-08])

In [5]:
def logisticRegression(X, theta):
    return sigmoid(X@theta)

In [6]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [7]:
def costFunction(theta,X,Y,lam):
    z = X@theta
    h = sigmoid(z)
    return (1/X.shape[0])*(-Y.T@np.log(h)-(1-Y).T@np.log(1-h)+(lam/2)*theta.T@theta)

In [8]:
X = np.array(([1,2,4],[1,4,5]))
Y = np.array(([0], [1]))
theta = np.zeros((3, 1))
lam = 0

In [9]:
fmin_l_bfgs_b(func=costFunction,x0=theta,approx_grad=True,args=(X,Y,lam))

(array([-6.0621115 , 16.72335723, -9.82368583]),
 array([7.4547258e-06]),
 {'funcalls': 96,
  'grad': array([-7.27206838e-07, -9.65902908e-06, -7.02223771e-06]),
  'nit': 19,
  'task': b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL',
  'warnflag': 0})